**Clean and prepare your data:**

**1. load both csv files**

In [117]:
import pandas as pd

train = pd.read_csv("M7 model.csv")
train.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A22,A23,A24,A25,A26,A27,A28,A29,A30,default
0,10.69,86.10,8920.16,19912.85,30.42,31.72,1.18,145.41,2.236,1.786,...,0.01,0.01,0.01,0.13,0.00,0.00,0.00,0.00,0.00,0
1,28.50,65.19,6564.00,6716.67,32.50,23.40,2.74,91.11,1.000,1.000,...,0.06,0.01,0.00,0.09,285.80,0.00,16.44,1.98,42.26,0
2,24.87,73.79,4285.47,6463.75,40.50,51.53,2.84,93.90,2.400,1.400,...,0.08,0.02,0.02,0.44,494.62,135.41,127.45,46.00,14.92,0
3,13.64,85.82,6887.56,9244.44,49.56,53.44,0.36,171.45,1.875,2.167,...,0.03,0.01,0.00,0.05,1015.19,0.00,210.63,92.58,0.00,0
4,4.50,95.92,8746.50,19987.50,32.75,37.88,0.92,153.25,2.000,1.500,...,0.01,0.00,0.00,0.04,0.00,106.41,79.00,0.00,0.00,0

In [118]:
import pandas as pd

val = pd.read_csv("M7 val.csv")
val.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A22,A23,A24,A25,A26,A27,A28,A29,A30,default
0,22.88,75.59,3367.08,6131.31,41.38,43.08,2.13,102.67,0.500,0.500,...,0.08,0.00,0.05,0.17,0.00,1035.14,158.71,13.28,0.00,1
1,15.94,86.26,5595.00,10867.86,52.29,61.21,3.05,124.94,3.200,2.400,...,0.01,0.00,0.00,0.06,438.50,0.00,72.78,44.88,25.39,1
2,25.16,64.20,4758.44,7818.15,46.28,50.72,2.69,110.16,1.124,0.889,...,0.08,0.02,0.02,0.10,622.70,755.52,102.89,6.24,0.00,1
3,19.50,77.81,5762.27,6290.00,58.14,76.27,2.44,119.92,1.222,1.000,...,0.04,0.00,0.01,0.08,197.55,396.27,76.34,8.44,2.00,1
4,11.11,85.09,11400.50,20936.25,30.00,29.75,0.50,125.89,2.167,1.333,...,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.00,0.00,1

**2. inspecting the data briefly, looking at columns and info**

In [119]:
print(train.columns)
print(val.columns)

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21',
       'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30',
       'default'],
      dtype='object')
Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'A11',
       'A12', 'A13', 'A14', 'A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21',
       'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30',
       'default'],
      dtype='object')

In [120]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94000 entries, 0 to 93999
Data columns (total 31 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   A1       94000 non-null  float64
 1   A2       94000 non-null  float64
 2   A3       94000 non-null  float64
 3   A4       94000 non-null  float64
 4   A5       94000 non-null  float64
 5   A6       94000 non-null  float64
 6   A7       94000 non-null  float64
 7   A8       94000 non-null  float64
 8   A9       94000 non-null  float64
 9   A10      94000 non-null  float64
 10  A11      94000 non-null  float64
 11  A12      94000 non-null  float64
 12  A13      94000 non-null  float64
 13  A14      94000 non-null  float64
 14  A15      94000 non-null  float64
 15  A16      94000 non-null  float64
 16  A17      94000 non-null  float64
 17  A18      94000 non-null  float64
 18  A19      94000 non-null  float64
 19  A20      94000 non-null  float64
 20  A21      94000 non-null  int64
 21  A22      94000 non-null  float64
 22  A23      94000 non-null  float64
 23  A24      94000 non-null  float64
 24  A25      94000 non-null  float64
 25  A26      94000 non-null  float64
 26  A27      94000 non-null  float64
 27  A28      94000 non-null  float64
 28  A29      94000 non-null  float64
 29  A30      94000 non-null  float64
 30  default  94000 non-null  int64
dtypes: float64(29), int64(2)
memory usage: 22.2 MB

**3. separate X and Y**

In [121]:
X_train = train.drop(columns=["default"])
y_train = train["default"]

X_val = val.drop(columns=["default"])
y_val = val["default"]

In [122]:
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

print(X_train.head())
print(y_train.value_counts(normalize=True))

(94000, 30) (94000,)
(11500, 30) (11500,)
      A1     A2       A3        A4     A5     A6    A7      A8     A9    A10  \
0  10.69  86.10  8920.16  19912.85  30.42  31.72  1.18  145.41  2.236  1.786
1  28.50  65.19  6564.00   6716.67  32.50  23.40  2.74   91.11  1.000  1.000
2  24.87  73.79  4285.47   6463.75  40.50  51.53  2.84   93.90  2.400  1.400
3  13.64  85.82  6887.56   9244.44  49.56  53.44  0.36  171.45  1.875  2.167
4   4.50  95.92  8746.50  19987.50  32.75  37.88  0.92  153.25  2.000  1.500

   ...  A21   A22   A23   A24   A25      A26     A27     A28    A29    A30
0  ...   10  0.01  0.01  0.01  0.13     0.00    0.00    0.00   0.00   0.00
1  ...   35  0.06  0.01  0.00  0.09   285.80    0.00   16.44   1.98  42.26
2  ...   31  0.08  0.02  0.02  0.44   494.62  135.41  127.45  46.00  14.92
3  ...   29  0.03  0.01  0.00  0.05  1015.19    0.00  210.63  92.58   0.00
4  ...   22  0.01  0.00  0.00  0.04     0.00  106.41   79.00   0.00   0.00

[5 rows x 30 columns]
default
0    0.957447
1    0.042553
Name: proportion, dtype: float64

**4. clean**

**explanatin**

- The assignment says there are deleted values to simulate dirty data, but there are no missing values. I'm assuming the missing values were replaced as zeros.
- inspecting to see which rows has an unusual amount of zeros compared to existing data

In [123]:
zero_pct = (X_train == 0).mean().sort_values(ascending=False)
print(zero_pct.head(10))

A23    0.600596
A30    0.547809
A24    0.430894
A27    0.376702
A26    0.301255
A19    0.290904
A29    0.251585
A18    0.192000
A28    0.144032
A16    0.137819
dtype: float64

In [124]:
high_zero_cols = zero_pct[zero_pct > 0.5]  # >50% zeros
print(high_zero_cols)

A23    0.600596
A30    0.547809
dtype: float64

In [125]:
print(X_train['A30'].describe())
print(X_train['A30'].value_counts().head(10))

count    94000.000000
mean        38.509910
std         90.882963
min       -719.720000
25%          0.000000
50%          0.000000
75%         49.862500
max      13487.000000
Name: A30, dtype: float64
A30
0.00     51494
19.88       35
10.00       32
25.00       30
14.92       24
4.97        24
20.00       24
9.97        22
19.98       21
1.00        21
Name: count, dtype: int64

**explanation**
- A30 has a high number of zeros. the zero in here looks like a placeholder for missing values since other existing values are larger

- A23 was also seen has a column with a lot of zeros, but when looking at the data, the other numbers in A23 are very close to zero, so it's not considered as an "unusual zeros column".

In [126]:
import numpy as np

# convert fake missing
X_train['A30'] = X_train['A30'].replace(0, np.nan)
X_val['A30'] = X_val['A30'].replace(0, np.nan)

# impute with median (from train only)
median_A30 = X_train['A30'].median()

X_train['A30'] = X_train['A30'].fillna(median_A30)
X_val['A30'] = X_val['A30'].fillna(median_A30)

**explanation**

- replaced the fake zeros with nan and fill it in with median value of the column
- feature engineering: Feature engineering involved identifying columns with suspicious zero values (e.g., A30) and treating them as missing. These values were imputed using the median of the training data to preserve distributional properties.

In [127]:
# scale feature
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)

In [128]:
# starting with logistic regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced', max_iter=1000)

model.fit(X_train_scaled, y_train)

y_prob = model.predict_proba(X_val_scaled)[:, 1]

**explanation**

- Starting with logistic regression as mentioned in the instructions. using standard scaler to scale features first
- from earlier inspection, it is shown that the data is very imbalanced
  - default:
  - 0    0.957447
  - 1    0.042553
  - almost 96% of the data is 0 (non-default), the model would lean towards predicting 0 all the time.
- using `class_weight = balanced` to balance the data, it gives class 1 a larger weight than class 0.

In [129]:
# save first file

pd.DataFrame(y_prob).to_csv("results1.csv", index=False, header=False)

In [130]:
# next model

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight='balanced',
    n_jobs=-1
)

In [131]:
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=300, n_jobs=-1,
                       random_state=42)

In [132]:
y_prob_rf = rf.predict_proba(X_val)[:, 1]

**explanation**

- using random forest for the second model.
- `n_estimatos` uses 300 trees to vote for the final decision
- also using class_weight balanced to balance the data
- using ChatGPT, it suggested using n_jobs = -1 to speed up the training process. it still works without it, but makes it more efficient
- Using random forest since logistic regression finds the linear relationship, and random forest can capture more complex relations. Random forest is also great for classifications

In [133]:
# save second file

pd.DataFrame(y_prob_rf).to_csv("results2.csv", index=False, header=False)

In [134]:
y_prob_rf[:5]

array([0.33333333, 0.02333333, 0.28      , 0.13333333, 0.00333333])

**explanation**

- checking the first few predictions
- the outputs look like probabilities
- output showing the probability belonging to the default class (labeled '1') as assignment mentioned

In [135]:
# just confirming the files
pd.read_csv("results2.csv").head()

   0.3333333333333333
0            0.023333
1            0.280000
2            0.133333
3            0.003333
4            0.440000

In [136]:
pd.read_csv("results1.csv").head()

   0.773076337492834
0           0.421393
1           0.823288
2           0.762455
3           0.128574
4           0.920281

In [145]:
print (roc_auc_score(y_val, y_prob))
print (roc_auc_score(y_val, y_prob_rf))

0.8203467333333334
0.8153839666666666

**explanation**

- using ROC AUC to evaluate the results. It meaures how well the model separates the classes (default and non default
- The results are pretty close for both models and both performed well